### ISSUE TITLE
SASでrawdataのcsv名が"xxx-xx.csv"のようにハイフンの入った文字列の場合に処理が欠落する

### ISSUE THREAD

**Issue by MarikoOhtsuka** [nnh/ptosh-format#21]
データセット名はアンダーバーに置換されて取り込まれるが、sheetのaliasnameがハイフンのままなのでヒットしない、たぶん

**Comment by MarikoOhtsuka** [comment]
`%CHANGE_DS_NAME;`の後に置換を入れたら対応できそう
```
%CHANGE_DS_NAME;

data sheet;
    set sheet;
    Sheet_alias_name = translate(Sheet_alias_name, '_', '-');
run;
```

**Comment by tosh13** [comment]
「データセット名はアンダーバーに置換されて取り込まれる」→どこのステップなのでしょうね。気になります。

**Comment by MarikoOhtsuka** [comment]
SASのデータセットの命名規則で、使用できる記号はアンダーバーのみとなっています。
rawdataのCSVファイルを取り込むときにalias nameをデータセット名として使用するので、alias nameのハイフンをアンダーバーに置換する処理を入れています。
https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/lepg/n1ov28a8jt7jx9n1op0ti5y0wj1d.htm#n1o0decx4v0vbun10flew5xmvat2

**Comment by tosh13** [comment]
ということは本質的にはaliasnameでハイフンを禁止するという考えもありますが、あまり気が進みませんね。了解しました。
